# Generated by Django 2.2.5 on 2019-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='image',
            field=models.ImageField(default='no_image.png', upload_to='profile_images'),
        ),
    ]
