# Generated by Django 2.2.5 on 2019-09-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190918_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
