# Generated by Django 2.2.5 on 2019-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190918_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='image',
            field=models.ImageField(default='profile_images/no_image.png', upload_to='profile_images'),
        ),
    ]
